name: snowflake-iac
on:
  pull_request: { branches: [ main ] }   # PRで plan
  push:         { branches: [ main ] }   # main 直pushで apply

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::321688112405:role/github-oidc-terraform

jobs:
  plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.8
    permissions:
      id-token: write   # OIDC 必須
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # (A) Snowflake鍵を書き出し＆SNOWFLAKE_* をエクスポート
      - name: Export Snowflake envs
        shell: bash
        run: |
          base64 -d <<< "${{ secrets.PRIVATE_KEY_B64 }}" > /tmp/sf_key.pem
          chmod 600 /tmp/sf_key.pem

          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SF_ACCOUNT }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ secrets.SF_USER }}"       >> $GITHUB_ENV
          echo "SNOWFLAKE_ROLE=SECURITYADMIN"                >> $GITHUB_ENV
          echo "SNOWFLAKE_REGION=ap-northeast-1"             >> $GITHUB_ENV
          echo "SNOWFLAKE_AUTHENTICATOR=SNOWFLAKE_JWT"       >> $GITHUB_ENV
          echo "SNOWFLAKE_PRIVATE_KEY_PASSPHRASE=${{ secrets.SF_KEY_PASSPHRASE }}" >> $GITHUB_ENV
          {
            echo "SNOWFLAKE_PRIVATE_KEY<<'EOF'"
            cat /tmp/sf_key.pem
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Terraform init (reconfigure & upgrade)
        run: terraform init -input=false -reconfigure -upgrade

      - name: Show provider resolution
        run: |
          terraform version
          terraform providers
          echo "---- lock file (head) ----"
          sed -n '1,120p' .terraform.lock.hcl || true

      - name: Terraform validate
        run: terraform validate

      # (B) Terraform 実行
      - name: Terraform plan
        run: terraform plan -no-color -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with: { name: tfplan, path: tfplan }

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.8
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: tfplan, path: . }

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Export Snowflake envs
        shell: bash
        run: |
          base64 -d <<< "${{ secrets.PRIVATE_KEY_B64 }}" > /tmp/sf_key.pem
          chmod 600 /tmp/sf_key.pem
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SF_ACCOUNT }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ secrets.SF_USER }}"       >> $GITHUB_ENV
          echo "SNOWFLAKE_ROLE=SECURITYADMIN"                >> $GITHUB_ENV
          echo "SNOWFLAKE_REGION=ap-northeast-1"             >> $GITHUB_ENV
          echo "SNOWFLAKE_AUTHENTICATOR=SNOWFLAKE_JWT"       >> $GITHUB_ENV
          echo "SNOWFLAKE_PRIVATE_KEY_PASSPHRASE=${{ secrets.SF_KEY_PASSPHRASE }}" >> $GITHUB_ENV
          {
            echo "SNOWFLAKE_PRIVATE_KEY<<'EOF'"
            cat /tmp/sf_key.pem
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Terraform init (reconfigure)
        run: terraform init -input=false -reconfigure

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan

